version = 0.1

[default.deploy.parameters]
stack_name = "github-api-metrics"
resolve_s3 = true
s3_prefix = "github-api-metrics"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
